{
  "language": "java",
  "jdk": "oraclejdk8",
  "script": [
    "mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar"
  ],
  "group": "stable",
  "dist": "precise",
  "os": "linux"
}
